name: flutter_lms_cambaya
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  google_fonts: 2.3.2
  flutter_svg: 1.0.3
  dropdown_button2: 1.4.0
  carousel_slider: 4.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  uses-material-design: true

